# Generated by Django 4.2.25 on 2025-11-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='app_seller_detailss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('total_sales', models.IntegerField(max_length=100)),
                ('no_of_sales', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='app_seller_details',
        ),
    ]
