# Generated by Django 4.2.25 on 2025-11-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0005_alter_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_seller_detailss',
            name='no_of_sales',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='app_seller_detailss',
            name='total_sales',
            field=models.IntegerField(),
        ),
    ]
